apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          #requiredDuringSchedulingIgnoredDuringExecution:
           # nodeSelectorTerms:
            #  - matchExpressions:
             #     - key: rank
              #      operator: Lt
               #     values: ["5"]
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                  - key: team
                    operator: In
                    values: ["prod"]
            - weight: 40
              preference: 
                matchExpressions:
                  - key: "rank"
                    operator: Gt
                    values: ["5"]
      containers:
        - name: nginxxontainer
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec: 
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 32100
      port: 80
      targetPort: 80
  