apiVersion: v1
kind: Pod
metadata:
  name: "one"
  labels:
    app: one
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort:  80
---
apiVersion: v1
kind: Pod
metadata:
  name: "two"
  labels:
    app: two
spec:
  affinity:
    #podAntiAffinity
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values: ["one"]
          topologyKey: kubernetes.io/hostname
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort:  80