apiVersion: v1
kind: Pod
metadata:
  name: pod
spec: 
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "prod"
      effect: "NoSchedule"
  containers:
    - image: nginx
      name: nginx-pod
      ports:
        - containerPort: 80