apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:4.0.8
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          command:
            - "mongod"
            - "--bind_ip_all"
            - "--config=/etc/mongo/mongodb.conf"
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 2
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 5
            periodSeconds: 10              
          volumeMounts:
            - name: mongo-volume
              mountPath: /etc/mongo
      volumes:
        - name: mongo-volume
          configMap:
            name: mongodb-config
            items:
              - key: mongodb.conf
                path: mongodb.conf
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  ports:
    - nodePort: 32100
      port: 27017
      targetPort: 27017
  selector:
    app: mongo