apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
    - type: Pod
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: "2"
        memory: 5Gi
    - type: Container
      min:
        cpu: 50m
        memory: 5Mi
      max: 
        cpu: "2"
        memory: 5Gi
      defaultRequest:
        cpu: 100m
        memory: 10Mi
      default:
        cpu: 200m
        memory: 100Mi
      maxLimitRequestRatio:
        cpu: "4"
        memory: 10