apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
    - name: nginxcontainer
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 60m
          memory: 10Mi
        limits:
          cpu: "2"
          memory: 5Gi