apiVersion: v1
kind: Pod
metadata:
  name:  requests
spec:
  containers:
    - name: stress-container
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu","1","--vm","1","--vm-bytes","1G","--vm-hang","1"]
      resources:
        requests:
          cpu: "200m"
          memory: "200Mi"
        limits:
          cpu: "0.2m"
          memory: "1Gi"