apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testrolebinding
  namespace: test
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: test-sa
 #- apiGroup: rbac.authorization.k8s.io/v1
 #  kind: Group
 #  name: dev 
 #- apiGroup: rbac.authorization.k8s.io/v1
 #  kind: User
 #  name: bhaskar
roleRef:
    apiGroup: rbac.authorization.k8s.io/v1
    kind: Role
    name: testrole